swagger: "2.0"
info:
  version: 0.0.0
  title: Masters for Collection System  
  description: Specification of all the master data APIs required for Collection Management System.

host: phoenix-qa.egovernments.org
schemes:
  - https
basePath: '/collection/masters/v1/[API endpoint]'

paths: 
  /paymentModesNotAllowed/_create:     
    post:
      summary: Create Payment Modes Not allowed for the Department.
      description: Create Payment Modes Not allowed for the Department.
      parameters:
        - name: paymentModesNotAllowed
          in: body
          description: Payment Modes Not Allowed.
          required: true
          schema:
            $ref: '#/definitions/PaymentModesNotAllowedReq'
      responses:
        '201':
          description: Payment Modes Not allowed for the department mapped successfully.
          schema:
            $ref: '#/definitions/PaymentModesNotAllowedRes'
        '400':
          description: Invalid input.
      tags:
        - Payment Modes Not Allowed

  /bankAccountServiceMapping/_create:     
    post:
      summary: Create Bank Account Service Mapping for the given tenantId.
      description: Create new Bank Account Service Mapping with all the required parameters.
      parameters:
        - name: bankAccountServiceMapping
          in: body
          description: New Bank Account Service Mapping.
          required: true
          schema:
            $ref: '#/definitions/BankAccountServiceMappingReq'
      responses:
        '201':
          description: Bank Account Service Mapping created sucessfully.
          schema:
            $ref: '#/definitions/BankAccountServiceMappingRes'
        '400':
          description: tenantId was not provided or General service error
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'
      tags:
        - Bank Account Service Mapping  
        
    /bankAccountServiceMapping/_search:     
    post:
      summary: Search Bank Account Service Mapping for the given tenantId.
      description: Search new Bank Account Service Mapping with all the required parameters.
      parameters:
        - name: businessDetails
          in: query
          description: Business details mapped for bank account.
          required: fasle
          type: string
          items:
            type: string
        - name: bankAccount
          in: query
          description: Bank Account for Service Mapping.
          required: fasle
          type: string
      responses:
        '201':
          description: Bank Account Service Mapping searched sucessfully.
          schema:
            $ref: '#/definitions/BankAccountServiceMappingRes'
        '400':
          description: tenantId was not provided or General service error
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'
      tags:
        - Bank Account Service Mapping   
    
        
definitions:
  PaymentModesNotAllowedReq:
    type: object
    properties:
      tenantId:
        type: string
        description: Unique id of tenant.
        format: varchar
      RequestInfo:
        $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo'
      PaymentModesNotAllowed:
        $ref: '#/definitions/PaymentModesNotAllowed'
        
  PaymentModesNotAllowedRes:
    type: object
    properties:
      tenantId:
        type: string
        description: Unique id of tenant.
        format: varchar
      RequestInfo:
        $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ResponseInfo'
      PaymentModesNotAllowed:
        $ref: '#/definitions/PaymentModesNotAllowed'
        
  PaymentModesNotAllowed:
    type: object
    properties:
      department:
        type: object
        description: Reference from Common Services Department.
      modesNotAllowed:
        type: string
        description: Pipe seperated value needs to be persisted for modes not allowed ex. Cash|Cheque
        
  BankAccountServiceMappingReq:
    type: object
    properties:
      RequestInfo:
        $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo'
      BankAccountServiceMapping:
        type: array
        items: 
         $ref: '#/definitions/BankAccountServiceMapping'
        
  BankAccountServiceMappingRes:
    type: object
    properties:
      ResponseInfo:
        $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ResponseInfo'
      BankAccountServiceMapping:
        type: array
        items: 
         $ref: '#/definitions/BankAccountServiceMapping'
         
  BankAccountServiceMapping:
    type: object
    properties:
      id:
        type: Integer
        description: Unique identification for object
    - $ref: "https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/parameters/tenantId"
      businessCategory:
        $ref: "https://raw.githubusercontent.com/egovernments/egov-services/master/docs/egov-common-masters/contracts/v1-0-0.yml#/definitions/BusinessCategory"
      businessdetails:
        $ref: "https://raw.githubusercontent.com/egovernments/egov-services/master/docs/egov-common-masters/contracts/v1-0-0.yml#/definitions/BusinessDetails"
      bank:
        $ref: "https://raw.githubusercontent.com/egovernments/egov-services/master/docs/financials/egf-masters/contracts/v1-0-0.yml#/definitions/Bank"
      bankBranch:
        $ref: "https://raw.githubusercontent.com/egovernments/egov-services/master/docs/financials/egf-masters/contracts/v1-0-0.yml#/definitions/BankBranch"
      bankAccount:
        $ref: "https://raw.githubusercontent.com/egovernments/egov-services/master/docs/financials/egf-masters/contracts/v1-0-0.yml#/definitions/BankAccount"
  
