version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    links:
      - zookeeper:zk
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "egov.egf.budget.service.validated:1:1,egov.egf.budget.service.completed:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
  postgres:
    image: postgres:9.4
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypass
      
  egf-budget:
    image: egovio/egf-budget:latest
    ports:
      - "8080:8080"
      - "9091:9091"
    links:
      - postgres:pghost
    environment:
      - DB_HOST=pghost
      - DB_PORT=5432
      - DB_NAME=mydb
      - DB_USER=myuser
      - DB_PASSWORD=mypass
      - REDIS_HOST=redis
      - CORS_ENABLED=true
      - MASTER_SERVER=false
      
  egf-masters:
    image: egovio/egf-masters:latest
    ports:
      - "8080:8080"
      - "9090:9090"
    links:
      - postgres:pghost
    environment:
      - DB_HOST=pghost
      - DB_PORT=5432
      - DB_NAME=mydb
      - DB_USER=myuser
      - DB_PASSWORD=mypass
      - REDIS_HOST=redis
      - CORS_ENABLED=true
      - MASTER_SERVER=false