serviceMaps:
 serviceName: Works Services
 mappings:
 - version: 1.0
   name: Works Documents Create and Update
   description: Persists and updates works documents in egw_documentdetails table
   fromTopic: works.documentdetails.create
   isTransaction: true
   queryMaps:   
    - query: INSERT INTO egw_documentdetail(id, tenantid, objectid, objecttype, documenttype, filestore, latitude, longitude, description, dateofcapture, workprogress, createdby, createdtime, lastmodifiedby, lastmodifiedtime, deleted) VALUES  (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) on CONFLICT (id,tenantid) DO UPDATE SET
             filestore=EXCLUDED.filestore, documenttype= EXCLUDED.documenttype, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, description=EXCLUDED.description, dateofcapture=EXCLUDED.dateofcapture, workprogress=EXCLUDED.workprogress,
             lastmodifiedtime=EXCLUDED.lastmodifiedtime, lastmodifiedby=EXCLUDED.lastmodifiedby, deleted=EXCLUDED.deleted;
      basePath: $.documentDetails.*
      jsonMaps:

       - jsonPath: $.documentDetails.*.id

       - jsonPath: $.documentDetails.*.tenantId

       - jsonPath: $.documentDetails.*.objectId

       - jsonPath: $.documentDetails.*.objectType
         
       - jsonPath: $.documentDetails.*.documentType
       
       - jsonPath: $.documentDetails.*.fileStore
       
       - jsonPath: $.documentDetails.*.latitude
       
       - jsonPath: $.documentDetails.*.longitude
       
       - jsonPath: $.documentDetails.*.description
       
       - jsonPath: $.documentDetails.*.dateOfCapture
       
       - jsonPath: $.documentDetails.*.workProgress

       - jsonPath: $.documentDetails.*.auditDetails.createdBy

       - jsonPath: $.documentDetails.*.auditDetails.createdTime
         dbType: LONG
       
       - jsonPath: $.documentDetails.*.auditDetails.lastModifiedBy
       
       - jsonPath: $.documentDetails.*.auditDetails.lastModifiedTime
         dbType: LONG

       - jsonPath: $.documentDetails.*.deleted
         dbType: BOOLEAN



 - version: 1.0
   name: Estimate Appropriation
   description: Persists and updates Estimate Appropriation in egw_estimate_appropriation table
   fromTopic: works.estimateappropriation.create
   isTransaction: true
   queryMaps:
    - query: INSERT INTO egw_estimate_appropriation(
            id, tenantid, objecttype, objectnumber, budgetusage, createdby, createdtime, lastModifiedBy, lastModifiedTime, deleted) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) on CONFLICT (id,tenantid) DO UPDATE SET budgetusage= EXCLUDED.budgetusage, objectnumber=EXCLUDED.objectnumber, lastModifiedBy=EXCLUDED.lastModifiedBy, lastModifiedTime=EXCLUDED.lastModifiedTime, deleted=EXCLUDED.deleted;
      basePath: $.estimateAppropriations.*
      jsonMaps:

       - jsonPath: $.estimateAppropriations.*.id

       - jsonPath: $.estimateAppropriations.*.tenantId

       - jsonPath: $.estimateAppropriations.*.objectType

       - jsonPath: $.estimateAppropriations.*.objectNumber

       - jsonPath: $.estimateAppropriations.*.budgetUsage

       - jsonPath: $.estimateAppropriations.*.auditDetails.createdBy

       - jsonPath: $.estimateAppropriations.*.auditDetails.createdTime
         dbType: LONG

       - jsonPath: $.estimateAppropriations.*.auditDetails.lastModifiedBy

       - jsonPath: $.estimateAppropriations.*.auditDetails.lastModifiedTime
         dbType: LONG

       - jsonPath: $.estimateAppropriations.*.deleted
         dbType: BOOLEAN

 - version: 1.0
   name: Works Offline Status Update
   description: Update Offline Status in egw_offlinestatus table
   fromTopic: works-offlinestatus-update-validated
   isTransaction: true
   queryMaps:   
    - query: INSERT INTO egw_offlinestatus(
            id, objecttype, objectnumber, remarks, statusdate, status, createdby, 
            createdtime, tenantid,referencenumber, lastModifiedBy, lastModifiedTime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) on CONFLICT (id,tenantid) DO UPDATE SET statusdate= EXCLUDED.statusdate, remarks=EXCLUDED.remarks, lastModifiedBy=EXCLUDED.lastModifiedBy, lastModifiedTime=EXCLUDED.lastModifiedTime;
      basePath: $.offlineStatuses.*
      jsonMaps:
         
       - jsonPath: $.offlineStatuses.*.id
       
       - jsonPath: $.offlineStatuses.*.objectType
         
       - jsonPath: $.offlineStatuses.*.objectNumber
       
       - jsonPath: $.offlineStatuses.*.remarks

       - jsonPath: $.offlineStatuses.*.statusDate
         dbType: LONG
         
       - jsonPath: $.offlineStatuses.*.status
       
       - jsonPath: $.offlineStatuses.*.auditDetails.createdBy
       
       - jsonPath: $.offlineStatuses.*.auditDetails.createdTime
         dbType: LONG

       - jsonPath: $.offlineStatuses.*.tenantId

       - jsonPath: $.offlineStatuses.*.referenceNumber

       - jsonPath: $.offlineStatuses.*.auditDetails.lastModifiedBy
       
       - jsonPath: $.offlineStatuses.*.auditDetails.lastModifiedTime
         dbType: LONG
