swagger: "2.0"
info:
  description: |
    This is a sample server Petstore server.

  version: "1.0.0"
  title: Tenant
host: egov-micro-dev.egovernments.org
basePath: /tenant/v1/

paths:
  /tenant/_search:
    post:
      tags:
        - tenant
      summary: Retrieve tenant(s) using tenant code(s).
      description: ""
      operationId: searchTenant
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: code
          description: Tenant codes to retrieve the tenants. (AP.KURNOOL, AP.GUNTOOR etc.,)
          required: true
          type: array
          items:
            type: string
          collectionFormat: multi
      responses:
        200:
          description: Successful search.
          schema:
            $ref: '#/definitions/SearchTenantResponse'

  /tenant/_create:
    post:
      tags:
        - tenant
      summary: Create new tenant.
      description: ""
      operationId: createTenant
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: createTenantRequest
          schema:
            $ref: '#/definitions/CreateTenantRequest'
      responses:
        200:
          description: Successful creation.
          schema:
            $ref: '#/definitions/CreateTenantResponse'


definitions:
  Tenant:
    type: "object"
    properties:
      code:
        type: "string"
      description:
        type: "string"
      imageId:
        type: "string"
      logoId:
        type: "string"
      domainUrl:
        type: "string"
      type:
        type: "string"
        enum:
        - "CITY"
      city:
        $ref: "#/definitions/City"

  City:
    type: "object"
    properties:
      name:
        type: "string"
      localName:
        type: "string"
      districtCode:
        type: "string"
      districtName:
        type: "string"
      regionName:
        type: "string"
      longitude:
        type: "number"
      latitude:
        type: "number"

  ResponseInfo:
    type: "object"
    properties:
      apiId:
        type: "string"

  RequestInfo:
    type: "object"
    properties:
      apiId:
        type: "string"

  SearchTenantResponse:
    type: "object"
    properties:
      responseInfo:
        $ref: "#/definitions/ResponseInfo"
      tenant:
        type: "array"
        items:
          $ref: "#/definitions/Tenant"

  CreateTenantRequest:
    type: "object"
    properties:
      RequestInfo:
        $ref: "#/definitions/RequestInfo"
      tenant:
        $ref: "#/definitions/Tenant"

  CreateTenantResponse:
    type: "object"
    properties:
      responseInfo:
        $ref: "#/definitions/ResponseInfo"
      tenant:
        $ref: "#/definitions/Tenant"


